/* eslint-disable import/prefer-default-export */

// home route actions
export const HOME_GET_BLOG_LIST = 'HOME_GET_BLOG_LIST';
export const HOME_GET_BLOG_LIST_SUCCESS = 'HOME_GET_BLOG_LIST_SUCCESS';
export const HOME_GET_BLOG_LIST_ERROR = 'HOME_GET_BLOG_LIST_ERROR';

export const HOME_GET_ARTICLES_FOR_BLOG = 'HOME_GET_ARTICLES_FOR_BLOG';
export const HOME_GET_ARTICLES_FOR_BLOG_SUCCESS = 'HOME_GET_ARTICLES_FOR_BLOG_SUCCESS';
export const HOME_GET_ARTICLES_FOR_BLOG_ERROR = 'HOME_GET_ARTICLES_FOR_BLOG_ERROR';

export const HOME_BLOG_PROPOSAL_URL_CHANGE = 'HOME_BLOG_PROPOSAL_URL_CHANGE';

// login route actions
export const LOGIN_USER_CHANGED = 'LOGIN_USER_CHANGED';
export const LOGIN_PASSWORD_CHANGED = 'LOGIN_PASSWORD_CHANGED';
