/* eslint-disable import/prefer-default-export */

export const HOME_GET_BLOG_LIST = 'HOME_GET_BLOG_LIST';
export const HOME_GET_BLOG_LIST_SUCCESS = 'HOME_GET_BLOG_LIST_SUCCESS';
export const HOME_GET_BLOG_LIST_ERROR = 'HOME_GET_BLOG_LIST_ERROR';

export const HOME_GET_ARTICLES_FOR_BLOG = 'HOME_GET_ARTICLES_FOR_BLOG';
export const HOME_GET_ARTICLES_FOR_BLOG_SUCCESS = 'HOME_GET_ARTICLES_FOR_BLOG_SUCCESS';
export const HOME_GET_ARTICLES_FOR_BLOG_ERROR = 'HOME_GET_ARTICLES_FOR_BLOG_ERROR';
