/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface definitions {
  user: {
    id: number;
    name?: string;
    email: string;
    role: 'USER' | 'ADMIN';
    createdAt?: string;
    updatedAt?: string;
  };
  data: {
    id: string;
    validUntil: string;
    userId: number;
    createdAt?: string;
    updatedAt?: string;
    user: definitions['user'];
  };
  Model1: { data: definitions['data'] };
  Model2: { email: string; password: string };

  getAuthMe200Response: definitions['Model1'];
  postAuthLoginRequestBody: definitions['Model2'];

  postAuthLoginDefaultResponse: string;

  postAuthLogoutDefaultResponse: string;
  postAuthRegisterRequestBody: definitions['Model2'];

  postAuthRegisterDefaultResponse: string;

  pathsDefinitions: {
    '/auth/me': {
      GET: {
        response: definitions['Model1'];
      };
    };
    '/auth/login': {
      POST: {
        requestBody: definitions['Model2'];

        response: string;
      };
    };
    '/auth/logout': {
      POST: {
        response: string;
      };
    };
    '/auth/register': {
      POST: {
        requestBody: definitions['Model2'];

        response: string;
      };
    };
  };
}
